# Generated by Django 4.2.1 on 2023-05-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_rename_qunatity_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
